name: Supremo CICD

on:
  push:
    branches:
      - main
      
jobs:   
  build_supremo_app:
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      REACT_APP_CARLIST_URL: http://api-supremo.oracledemo.online/car-service-redis/cars
      REACT_APP_CARAPP_LOGINAUTH_URL: http://api-supremo.oracledemo.online/user-service-redis/authn
      REACT_APP_GET_USER_BY_ID: http://api-supremo.oracledemo.online/user-service-redis/users/
      REACT_APP_CREATE_ORDER_API: http://api-supremo.oracledemo.online/order-service/create-order
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: frontend/supremo-reactjs
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.get-ocir-repository.outputs.repo_path }}
          tags: |
            type=sha,prefix=

      - name: Login to OCI Container Registry
        uses: docker/login-action@v3
        with:
          registry: bom.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        working-directory: frontend
        run: npm list

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build supremo app
        working-directory: frontend
        run: CI=false npm run build

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: frontend/.
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  deploy_app:
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    runs-on: ubuntu-latest
    needs:
      - build_supremo_app
    steps:
      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: frontend/supremo-reactjs
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.get-ocir-repository.outputs.repo_path }}
          tags: |
            type=sha,prefix=

      - name: Deploy via OCI DevOps Deployment Pipeline
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
            command: devops deployment create-pipeline-deployment --pipeline-id ${{ secrets.OCI_DEVOPS_PIPELINE_ID }} --deployment-arguments "{\"items\":[{\"name\":\"IMG\",\"value\":\"${{ steps.get-ocir-repository.outputs.repo_path }}:${{ steps.meta.outputs.version }}\"}]}"
            silent: true